name: Changeset Status

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "demo/**" # Monitor changes in this directory

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changesets_check:
    name: 🦋 [changesets] check for changeset
    runs-on: ubuntu-large
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.7.6

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run changeset status
        run: pnpm changeset:status
